### ISSUE TITLE
`playbook` must be set for the Ansible provisioner.

### ISSUE THREAD

**Issue by andyknownasabu** [palkan/sharelatex-vagrant-ansible#8]
I pulled the latest version from git yesterday and now I see the following error message:

There are errors in the configuration of this machine. Please fix
the following errors and try again:
ansible provisioner:
* `playbook` must be set for the Ansible provisioner.

**Comment by pavelbinar** [comment]
Hi @palkan 
I am having same problem. Any idea how to fix it?
Thanks!

**Comment by palkan** [comment]
Fixed.
